security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_register:
            pattern: ^/api/register$
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }

        - { path: ^/api/themes, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/cours, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/lecons, methods: [GET], roles: PUBLIC_ACCESS }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/formateur, roles: ROLE_FORMATEUR }